### ISSUE TITLE
OAuth 1 setAccessToken does not work

### ISSUE THREAD

**Issue by shellprog** [daviddesberg/PHPoAuthLib#393]
For OAuth 1 (Bitbucket) it is unable to store access token . I have access token in db , but unable to set it during request .

```
 $fs = OAuth::consumer('BitBucket');
 $token_interface = new \OAuth\OAuth1\Token\StdOAuth1Token($token);
 $fs->getStorage()->storeAccessToken('BitBucket', $token_interface);
 $result = json_decode($fs->request('user/repositories'));
```

Result is null , not sure what is wrong .

Help is appreciated .

**Comment by logical-and** [comment]
Take a look on [this example](https://github.com/logical-and/php-oauth/blob/master/examples/google_offline.php). Does it gives you any answers?
