### ISSUE TITLE
Reciving the HTTP status code of the response?

### ISSUE THREAD

**Issue by RobinBertilsson** [daviddesberg/PHPoAuthLib#539]
So, lets say you're creating a request whatever domain you'd like.
You probably doing something like `$response = $service->request('endpoint', 'GET')`.

But the `$response` variable will ONLY contain the body of the response.
We're having a senario where the provider returns a 401, can clearly see it in CurlClient.php@126, but since `retrieveResponse()` only returning `curl_exec($ch)` it's pretty hard to solve.

Whats the thoughts here?

**Comment by germanow** [comment]
I found this PR https://github.com/Lusitanian/PHPoAuthLib/pull/236 , but it wasn't accepted.
